# Autoconfiguration for lectures notes
# (c) 2012, Christian Rinderknecht (rinderknecht@free.fr)
#
# You may freely modify and redistribute, as long as I am credited as
# the original author.
#
# Process this file with `autoconf' to produce a configure script.

AC_INIT
AC_CONFIG_SRCDIR

AC_PATH_PROG(TOUCH,touch,none)
AC_PATH_PROG(ECHO,echo,none)
AC_PATH_PROG(RM,rm,none)
AC_PATH_PROG(PRINTF,printf,none)
AC_PATH_PROG(A2PS,a2ps,none)
AC_PATH_PROG(JAVA,java,none)
AC_PATH_PROG(JAVAC,javac,none)
AC_PATH_PROG(HTML2PS,html2ps,none)
AC_PATH_PROG(PS2PDF,ps2pdf,none)
AC_PATH_PROG(XMLLINT,xmllint,none)
AC_PATH_PROG(GCC,gcc,none)
AC_PATH_PROG(ERLC,erlc,none)
AC_PATH_PROG(SWIPL,swipl,none)
AC_PATH_PROG(GS,gs,none)

AC_SUBST(TOUCH)
AC_SUBST(ECHO)
AC_SUBST(RM)
AC_SUBST(PRINTF)
AC_SUBST(A2PS)
AC_SUBST(HTML2PS)
AC_SUBST(PS2PDF)
AC_SUBST(XMLLINT)
AC_SUBST(JAVA)
AC_SUBST(JAVAC)
AC_SUBST(GCC)
AC_SUBST(ERLC)
AC_SUBST(SWIPL)
AC_SUBST(GS)

AC_CONFIG_FILES([common.mk])
AC_OUTPUT
chmod a-w common.mk
